### ISSUE TITLE
如果使用的是 AC 866M 的 拆机无线网卡的同学可能需要移除部分驱动才能正常使用蓝牙

### ISSUE THREAD

**Issue by tanpengsccd** [zanjie1999/Lenovo-M710q-QNCT-DW1560-Hackintosh#1]
给一个删除了 干扰项的配置截图

![image](https://user-images.githubusercontent.com/13959880/129058125-70d2f569-e9e7-4d03-9197-89df0b7c3874.png)

**Comment by tanpengsccd** [comment]
随航 AW解锁都能正常开启.

**Comment by zanjie1999** [comment]
这是给dw1560也就是94352z用的

**Comment by zanjie1999** [comment]
欢迎fork走然后改一下
